runtime: nodejs
env: standard

handlers:
  - url: /.*
    script: auto

instance_class: F2

env_variables:
  PORT: 3000
  PROJECT_ID: submissionmlgc-faridradityo
  GOOGLE_CLOUD_CREDENTIALS: submissionmlgc-faridradityo-e57bb87569d4.json
  DATABASE_ID: ambapredict

# Optional: Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5

# Optional: Error reporting
error_reporting:
  enable_error_reporting: true
